version: '3.7'

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      # ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      # xpack.security.enabled: ${ELASTIC_SECURITY}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
      # - elasticsearch-data:/usr/share/elasticsearch/data
      # - ./.docker/elasticsearch/:/usr/share/elasticsearch/config/
    networks:
      - app-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    ports:
      - 5601:5601
    # environment:
      # ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      # ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
      # ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    # volumes:
      # - kibana-data:/usr/share/kibana/data
      # - ./.docker/kibana/:/usr/share/kibana/config/
    networks:
      - app-network

# volumes:
  # kibana-data:
    # driver: local
  # elasticsearch-data:
    # driver: local

networks:
  app-network:
    driver: bridge
