version: '3.7'

services:

  elasticsearch:
    container_name: es-node01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app-network

  kibana:
    container_name: kib-01
    image: docker.elastic.co/kibana/kibana:8.3.1
    ports:
      - 5601:5601
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
