version: '3.7'

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      # - ./.docker/elasticsearch/:/usr/share/elasticsearch/config/
    networks:
      - app-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.3.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - kibana-data:/usr/share/kibana/data
      # - ./.docker/kibana/:/usr/share/kibana/config/
    networks:
      - app-network

volumes:
  kibana-data:
    driver: local
  elasticsearch-data:
    driver: local

networks:
  app-network:
    driver: bridge
